[shmimMonitor]
shmimName=camacq_avg

#[darkShmim]
#shmimName=camacq_fit

#[framegrabber]
#shmimName=camacq_acq

[fitter]
fpsSource=camacq
max_loops=7
zero_area=60
threshold=20
fwhm_threshold=6 

[acquisition]
x_center=345
y_center=325
