[shmimMonitor]
shmimName=camacq_avg

#[darkShmim]
#shmimName=camacq_fit

#[framegrabber]
#shmimName=camacq_acq

[fitter]
fpsSource=camacq_avg
max_loops=7
zero_area=60
threshold=10
fwhm_threshold=4 

[acquisition]
x_center=345
y_center=325
