include=header_common,header_holoop,header_coronagraph,header_loloop

[fwfpm]
telem_stage=presetName,preset
telem_position=pos

[stagevp]
telem_stage=presetName,preset
telem_zaber=pos

[stageirf]
telem_stage=presetName,preset
telem_zaber=pos

[camdurham]
telem_stdcam=xcen,ycen,width,height,xbin,ybin,fps,temp,tempSetpt,tempStatus,tempOnTarget,tempStatusStr
