[power]
device=pdu3
channel=camvisx

[camera]
fanSpeedControl=true
defaultFanSpeed=off
startupLED=false

[framegrabber]
shmimName=camdurham
circBuffLength=1
latencyTime=2
latencySize=20000
defaultFlip=flipUD
