[shmimMonitor]
shmimName=camflowfs
cpuset=camflowfs_fit

[darkShmim]
shmimName=camflowfs_dark

[refShmim]
shmimName=aol2_wfsref

[framegrabber]
shmimName=camflowfs_fit
cpuset=camflowfs_fit

[fitter]
fpsSource=camflowfs
