[shmimMonitor]
shmimName=camflowfs_avg
cpuset=camflowfs_avg_fit

#[darkShmim]

[refShmim]
shmimName=aol2_wfsref

[framegrabber]
shmimName=camflowfs_avg_fit
cpuset=camflowfs_avg_fit

[fitter]
fpsSource=camflowfs-avg
