[shmimMonitor]
shmimName=camflowfs_avg
cpuset=camflowfs_avg_fit
threadPrio=1 #lower than framegrabber


[refShmim]
shmimName=aol2_wfsref

[framegrabber]
shmimName=camflowfs_avg_fit
cpuset=camflowfs_avg_fit
threadPrio=2 #higher tha shmimMOnitor
latencyTime=10
latencySize=100000


[fitter]
fpsDevice=camflowfs-avg
fpsProperty=fg_timing
fpsElement=write_fps
fpsTol=5 #make big so we don't constantly reallocate

shutterDevice=camflowfs
