[shmimMonitor]
shmimName=camllowfs
cpuset=camllowfs_fit

[darkShmim]
shmimName=camllowfs_dark

[refShmim]
shmimName=aol2_wfsref

[framegrabber]
shmimName=camllowfs_fit
cpuset=camllowfs_fit

[fitter]
fpsDevice=camllowfs
