include=header_common,
include=header_holoop,
include=header_coronagraph,
include=header_loloop,
include=header_camsci

[fwsci2]
telem_stage=presetName,preset
telem_position=pos

[stagesci2]
telem_stage=presetName,preset
telem_zaber=pos

[camsci2]
telem_stdcam=xcen,ycen,width,height,xbin,ybin,fps,emGain,adcSpeed,temp,tempSetpt,tempStatus,tempOnTarget,tempStatusStr,shutterState,vshift,synchro
