include=header_common,header_holoop,header_coronagraph,header_loloop,header_camsci

[fwsci2]
telem_stage=presetName,preset
telem_position=pos

[stagesci2]
telem_stage=presetName,preset
telem_zaber=pos

[camsci2]
telem_stdcam=xcen,ycen,width,height,xbin,ybin,fps,emGain,adcSpeed,temp,tempSetpt,tempStatus,tempOnTarget,tempStatusStr,shutterState,vshift,synchro
