[power]
device=pdu2
channel=camsci1
powerOnWait=5

[camera]
serialNumber=09434117
startupTemp=-50
fanSpeedControl=true
defaultFanSpeed=off

[framegrabber]
circBuffLength=1 
cpuset=camsci1
defaultFlip=flipLR

[shutter]
powerDevice=dcdu1
powerChannel=shsci1
dioDevice=xt1121_2
sensorChannel=ch01
triggerChannel=ch05

[synchro]
deviceName=fxngensync
channel=C2
otherCamName=camsci2
