#targetXc=0.568
#targetYc=0.603

[camera]
serialNumber=22636058
default_y=240
default_x=400
default_w=128
default_h=128
default_bin_x=1
default_bin_y=1

[framegrabber]
shmimName=camtip
circBuffLength=1
defaultFlip=flipLR

latencyTime=10
latencySize=100000

cpuset=camtip
