[shmimMonitor]
shmimName= aol1_imWFS2
cpuset=acqu_mvm
threadPrio=45

[parameters]
dataDirs = /data/users/xsup/MachineLearning/2024B_OnSky/Models
engineDirs = /data/users/xsup/MachineLearning/2024B_OnSky/Models
onnxFileName = test_model_20241119_faint.onnx
#engineName = 20250408_nd2_2_fp16.trt
engineName = 20250415_nd2_3.6khz_withtiptilt_driftcorr_L1reg2.trt
channel = aol1_modevalWFS
#channel = dm01disp09

imageNorm = 1
modalNorm = 1
m_pupPix = 64
pup_offset1_x = 0
pup_offset1_y = 0
pup_offset2_x = 60
pup_offset2_y = 60


