[shmimMonitor]
shmimName= aol1_imWFS2
cpuset=acqu_mvm
threadPrio=45

[parameters]
dataDirs = /srv/aoc/home/rlandman/data/MachineLearning/Models/
engineDirs = /srv/aoc/home/rlandman/data/MachineLearning/Models/
engineName = 20251205_ND4_cont3_fp16.trt
channel = aol1_modevalWFS
#channel = dm01disp09
use_fp16 = false
explicit_tt = false

imageNorm = 1
modalNorm = 1
m_pupPix = 64
pup_offset1_x = 0
pup_offset1_y = 0
pup_offset2_x = 60
pup_offset2_y = 60

