[shmimMonitor]
shmimName=aol1_imWFS2
cpuset=acqu_mvm
threadPrio=45

[parameters]
dataDirs= /data/users/xsup/MachineLearning/2024B_OnSky/Models
engineDirs= /data/users/xsup/MachineLearning/2024B_OnSky/Models
onnxFileName = test_model_20241114.onnx
engineName = test_build_20241115
rebuildEngine = false
channel = aol1_modevalWFS
imageNorm = 1.
modalNorm = 1.
m_pupPix = 60
pup_offset1_x = 0
pup_offset1_y = 0
pup_offset2_x = 60
pup_offset2_y = 60
padding_size = 2
