[shmimMonitor]
#shmimName=dm00disp
shmimName=dm00disp_delta

#[darkShmim]
#shmimName=dm00disp00

[framegrabber]
shmimName=dmwoofer_avg 

[integrator]
fpsSource=t2wOffloader
avgTime=1.0
#nAverage=1000

