[pdu0]
adminChannels=compicc,comprtc,dcpwr,swinst
userChannels=source,ttmperi

[pdu1]
userChannels=camwfs,dmncpc,dmtweeter,picomotors,stagesmc,ttmmod,ttmpupil

[pdu2]
adminChannels=camflowfs,camllowfs
userChannels=camsci1,camsci2,dmwoofer,stagezaber

[pdu3]
adminChannels=blower,fanaux,fanmain,instcool
userChannels=camvisx,flippers,stageff,tableair

[dcdu0]
userChannels=fwfpm,fwlowfs,fwlyot,fwpupil,fwsci1,fwsci2

[dcdu1]
userChannels=fwscind,fwtelsim,shllowfs,shlowfs,shsci1,shsci2,shwfs

[usbdu0]
adminChannels=rhtweeter
userChannels=camacq,camtip,flipacq,fliptip,flipwfsf,fwtelsim

[usbdu1]
adminChannels=rhncpc
userChannels=camvisx,fwscind,stagezaber

