[pdu0]
adminChannels=compicc,comprtc,dcpwr
userChannels=source,ttmperi

[pdu1]
userChannels=camwfs,dmncpc,dmtweeter,picomotors,stagesmc,ttmmod,ttmpupil

[pdu2]
userChannels=camsci1,camsci2,dmwoofer,stagepolrot,stageqwprot

[pdu3]
adminChannels=blower,rackfans,instcool,acc001
userChannels=camvisx,stageff,tableair

[dcdu0]
userChannels=fwfpm,fwlowfs,fwlyot,fwpupil,fwsci1,fwsci2

[usbdu0]
adminChannels=rhtweeter
userChannels=camacq,camtip

[usbdu1]
adminChannels=rhncpc
userChannels=camvisx,stagepolrot,stageqwprot

[vpdu0]
userChannels=camwfs,camsci1,camsci2,fwtelsim,fwscind,flippers
adminChannels=camflowfs,camllowfs,stagezaber