#FITS header common to all cameras downstream of camacq
#
include=header_input

[stagek]
telem_stage=presetName,preset
telem_position=pos

[stageadc1]
telem_stage=presetName,preset
telem_position=pos

[stageadc2]
telem_stage=presetName,preset
telem_position=pos



[hwptrack]
telem_poltrack=set_angle,actual_angle,pos_name,tracking

[stagepolrot]
telem_stage=presetName,preset
telem_zaber=pos


