#HO Loop FITS header

[stagescibs]
telem_stage=presetName,preset
telem_zaber=pos

[modwfs]
ttmmod_params=modState,modFreq,modRad,offset1,offset2

[flipwfsf]
telem_stage=presetName

[fliptip]
telem_stage=presetName

[camwfs]
telem_stdcam=fps,xbin,ybin,emGain
ocam_temps=ccd 

[holoop]
telem_loopgain=state,gain,multcoef,limit

[hogainctrl]
telem_blockgains=gains,gains_constant,mcs,mcs_constant,lims,lims_constant
