#FITS header for input parameters 

[observers]
telem_observer=email,obsName,operator_email,tgtName

[tcsi]
telem_telcat=catObj,catRA,catDec,catEp
telem_telpos=ra,dec,epoch,el,am,ha
telem_teldata=pa

[stagepollin]
telem_stage=presetName,preset
telem_zaber=pos

[fwtelsim]
telem_stage=presetName,preset

[stagepickoff]
telem_stage=presetName,preset
telem_position=pos

[flipacq]
telem_stage=presetName,preset


