[stagevp]
telem_stage=presetName,preset
telem_zaber=pos

[fwscind]
telem_stage=presetName,preset

[stagescibs]
telem_stage=preset,presetName

[tweeterSpeck]
telem_dmspeck=modulating,trigger,frequency,separations,angles,amplitudes,crosses
