
[observers]
telem_observer=email,obsName,operator_email,tgtName

[tcsi]
telem_telcat=catObj,catRA,catDec,catEp
telem_telpos=ra,dec,epoch,el,am,ha
telem_teldata=pa

[camwfs]
telem_stdcam=fps,xbin,ybin,emGain

[holoop]
telem_loopgain=state,gain,multcoef,limit

[fxngenmodwfs]
telem_fxngen=C1freq,C2freq

[stagebs]
telem_stage=presetName,preset
telem_zaber=pos

[tweeterSpeck]
telem_dmspeck=modulating,trigger,frequency,separations,angles,amplitudes,crosses


