[hwptrack]
telem_poltrack=set_angle,actual_angle,pos_name,tracking

[stagepolrot]
telem_position=pos

#[stagepollin]
#telem_stage=preset,presetName

[stagek]
telem_position=pos

[stageadc1]
telem_position=pos

[stageadc2]
telem_position=pos

[stagescibs]
telem_stage=preset,presetName


[tweeterSpeck]
telem_dmspeck=modulating,trigger,frequency,separations,angles,amplitudes,crosses
