
[fwlowfs]
telem_stage=presetName,preset
telem_position=pos

[stageflowfs]
telem_stage=presetName,preset
telem_zaber=pos 

[camflowfs]
telem_stdcam=fps

[stagellowfs]
telem_stage=presetName,preset
telem_zaber=pos 

[camllowfs]
telem_stdcam=fps

[loloop]
telem_loopgain=state,gain,multcoef,limit

[logainctrl]
telem_blockgains=gains,gains_constant,mcs,mcs_constant,lims,lims_constant
