[loop]
number=1
name=holoop
gainGain=0.1
gainLeak=0.98


[extrapolation]
method=power_law_only
powerLawAutoSmoothWidthHz=100
powerLawCrossoverMode=auto_smoothed_crossing
noiseEstimateDomain=closed_loop_pre_xfer
noiseEstimateRange=low_freq
noiseEstimateStatistic=minimum
noiseEstimateLowFreqMaxHz=100
closedLoopOlEstimateMethod=etf_only
