
[graph]
file=magaox.drawio

[source]
type=pwrOnOff
pwrKey=pdu0.source

[fwtelsim]
type=stdMotion
presetPrefix=filter

[pickoff]
type=stdMotion
device=stagepickoff
presetDir=input
presetPutName=lab,tel

[stagek]
type=stdMotion
trackingReqKey=labrules.info
trackingReqElement=teldome-open-not-lab
trackerKey=ktrack.tracking
trackerElement=toggle

