
[graph]
file=magaox.drawio

[telescope]
type=indiProp
propKey=tcsi.teldata
propEl=dome_stat
propVal=1

[source]
type=pwrOnOff
pwrKey=pdu0.source

[fwtelsim]
type=stdMotion
presetPrefix=filter

[stagepickoff]
type=stdMotion
device=stagepickoff
presetDir=input
presetPutName=lab,tel

[stagek]
type=stdMotion
trackingReqKey=labrules.info
trackingReqElement=teldome-open-stagepickoff-tel
trackerKey=ktrack.tracking
trackerElement=toggle

[ttmpupil]
type=fsm
fsmAction=active
targetStates=READY,OPERATING

[flipacq]
##type=stdMotion
##alwasOn=out
##auxOut=in
##auxOut-in=in #this specifies that the aux-output named in is on when the preset state is in
type=static
inputsOn=in
outputsOn=out

#
#[camacq]
#type=fsm
#fsmAction=active
#targetStates=OPERATING
#
#[dmwoofer]
#type=fsm
#fsmAction=active
#targetStates=OPERATING
#
#[dmtweeter]
#type=fsm
#fsmAction=active
#targetStates=OPERATING
#
#[stageadc1]
#type=stdMotion
#trackingReqKey=labrules.info
#trackingReqElement=teldome-open-stagepickoff-tel
#trackerKey=adctrack.tracking
#trackerElement=toggle
#
#[stageadc2]
#type=stdMotion
#trackingReqKey=labrules.info
#trackingReqElement=teldome-open-stagepickoff-tel
#trackerKey=adctrack.tracking
#trackerElement=toggle
#
