
[graph]
file=magaox.drawio
outputPath=/tmp/magaox.drawio

[telescope]
device=tcsi
type=indiProp
propKey=tcsi.teldata
propEl=dome_stat
propVal=1

[source]
type=pwrOnOff
pwrKey=pdu0.source

[fwtelsim]
type=stdMotion
presetPrefix=filter

[stagepickoff]
type=stdMotion
device=stagepickoff
presetDir=input
presetPutName=lab,tel

[stagek]
type=stdMotion
trackingReqKey=labrules.info
trackingReqElement=teldome-open-stagepickoff-tel
trackerKey=ktrack.tracking
trackerElement=toggle

[ttmpupil]
type=fsm
fsmAction=active
targetStates=READY,OPERATING

[flipacq]
type=stdMotion
presetPutName=out,in
alwaysOn=out
noAutoOn=in

[camacq]
type=fsm
fsmAction=active
targetStates=OPERATING

[dmwoofer]
type=fsm
fsmAction=active
targetStates=OPERATING

[dmtweeter]
type=fsm
fsmAction=active
targetStates=OPERATING

[stageadc1]
type=stdMotion
trackingReqKey=labrules.info
trackingReqElement=teldome-open-stagepickoff-tel
trackerKey=adctrack.tracking
trackerElement=toggle

[stageadc2]
type=stdMotion
trackingReqKey=labrules.info
trackingReqElement=teldome-open-stagepickoff-tel
trackerKey=adctrack.tracking
trackerElement=toggle

[ttmperi]
type=fsm
fsmAction=active
targetStates=OPERATING

[stageff]
type=static
inputsOn=in
outputsOn=out

[stagebs]
type=static
inputsOn=in
outputsOn=wfs,sci

[modwfs]
type=fsm
fsmAction=active
targetStates=READY,OPERATING


[flipwfsf]
type=stdMotion
alwaysOn=out

[fliptip]
type=stdMotion
presetPutName=out,in
alwaysOn=out
noAutoOn=in

[stagecamlensx]
type=fsm
fsmAction=active
targetStates=READY,OPERATING

[stagecamlensy]
type=fsm
fsmAction=active
targetStates=READY,OPERATING

[shwfs]
type=indiProp
device=camwfs
fsmPropName=shutter_status
fsmElName=status
targetStates=READY
propKey=camwfs.shutter
propEl=toggle
propVal=Off
onStr=OPEN
offStr=SHUT

[camwfs]
type=fsm
fsmAction=active
targetStates=OPERATING

[camtip]
type=fsm
fsmAction=active
targetStates=OPERATING



[dmncpc]
type=fsm
fsmAction=active
targetStates=OPERATING

[fwpupil]
type=stdMotion
presetPrefix=filter

[stagepiaa]
type=stdMotion

[picoscix]
type=fsm
device=picomotors
fsmAction=active
targetStates=READY,OPERATING

[fwfpm]
type=stdMotion
presetPrefix=filter
presetDir=input

[stagelosel]
type=stdMotion

[fwlowfs]
#type=stdMotion
#presetPrefix=filter
type=static
inputsOn=in
outputsOn=out

[shflowfs]
type=indiProp
device=camflowfs
fsmPropName=shutter_status
fsmElName=status
targetStates=READY
propKey=camflowfs.shutter
propEl=toggle
propVal=Off
onStr=OPEN
offStr=SHUT

[camflowfs]
type=fsm
fsmAction=active
targetStates=OPERATING

[stageflowfs]
type=fsm
targetStates=READY

[fwlyot]
type=stdMotion
presetPrefix=filter

[stageipiaa]
type=stdMotion

[stagefold]
type=static
inputsOn=in
outputsOn=in

[fwscind]
type=stdMotion
presetPrefix=filter

[stagescibs]
type=static
inputsOn=in
outputsOn=in,out

[fwsci1]
type=stdMotion
presetPrefix=filter

[shsci1]
type=indiProp
device=camsci1
fsmPropName=shutter_status
fsmElName=status
targetStates=READY
propKey=camsci1.shutter
propEl=toggle
propVal=Off
onStr=OPEN
offStr=SHUT

[camsci1]
type=fsm
fsmAction=active
targetStates=OPERATING

[stagesci1]
type=fsm
targetStates=READY

[fwsci2]
type=stdMotion
presetPrefix=filter

[shsci2]
type=indiProp
device=camsci2
fsmPropName=shutter_status
fsmElName=status
targetStates=READY
propKey=camsci2.shutter
propEl=toggle
propVal=Off
onStr=OPEN
offStr=SHUT

[camsci2]
type=fsm
fsmAction=active
targetStates=OPERATING

[stagesci2]
type=fsm
targetStates=READY
