
[graph]
file=/opt/MagAOX/config/magaox.drawio
outputPath=/tmp/magaox.drawio

[telescope]
type=indiProp
propKey=tcsi.teldata
propEl=dome_stat
propVal=1

[source]
type=pwrOnOff
pwrKey=pdu0.source

[fwtelsim]
type=stdMotion
presetPrefix=filter

[stagepickoff]
type=stdMotion
device=stagepickoff
presetDir=input
presetPutName=lab,tel

[stagek]
type=stdMotion
trackingReqKey=labrules.info
trackingReqElement=teldome-open-stagepickoff-tel
trackerKey=ktrack.tracking
trackerElement=toggle

[ttmpupil]
type=fsm
fsmAction=active
targetStates=READY,OPERATING

[flipacq]
##type=stdMotion
##alwasOn=out
##auxOut=in
##auxOut-in=in #this specifies that the aux-output named in is on when the preset state is in
type=static
inputsOn=in
outputsOn=in,out


[camacq]
type=fsm
fsmAction=active
targetStates=OPERATING

[dmwoofer]
type=fsm
fsmAction=active
targetStates=OPERATING

[dmtweeter]
type=fsm
fsmAction=active
targetStates=OPERATING

[stageadc1]
type=stdMotion
trackingReqKey=labrules.info
trackingReqElement=teldome-open-stagepickoff-tel
trackerKey=adctrack.tracking
trackerElement=toggle

[stageadc2]
type=stdMotion
trackingReqKey=labrules.info
trackingReqElement=teldome-open-stagepickoff-tel
trackerKey=adctrack.tracking
trackerElement=toggle

[ttmperi]
type=fsm
fsmAction=active
targetStates=OPERATING

[stageff]
type=static
inputsOn=in
outputsOn=out

[stagebs]
type=static
inputsOn=in
outputsOn=wfs,sci

[modwfs]
type=fsm
fsmAction=active
targetStates=READY,OPERATING


[flipwfsf]
type=stdMotion

[fliptip]
type=stdMotion
alwaysOn=out
auxOut:in=in #this specifies that the aux-output named in is on when the preset state is in

[stagecamlensx]
type=fsm
fsmAction=active
targetStates=READY,OPERATING

[stagecamlensy]
type=fsm
fsmAction=active
targetStates=READY,OPERATING

[shwfs]
type=indiProp
propKey=camwfs.shutter
propEl=toggle
propVal=Off

[camwfs]
type=fsm
fsmAction=active
targetStates=OPERATING


[dmncpc]
type=fsm
fsmAction=active
targetStates=OPERATING

[fwpupil]
type=stdMotion
presetPrefix=filter

[stagepiaa]
type=stdMotion

[picoscix]
type=fsm
device=picomotors
fsmAction=active
targetStates=READY,OPERATING

[fwfpm]
type=stdMotion
presetPrefix=filter
presetDir=input

[stagelosel]
type=stdMotion

[fwlowfs]
type=stdMotion
presetPrefix=filter

[shflowfs]
type=indiProp
propKey=camflowfs.shutter
propEl=toggle
propVal=Off

[camflowfs]
type=fsm
fsmAction=active
targetStates=OPERATING


[fwlyot]
type=stdMotion
presetPrefix=filter

[stageipiaa]
type=stdMotion

