[local]
#A/C power control:
drivers=pdu0,pdu1,pdu2,pdu3,
#Digital i/o:
drivers=xt1121_1,xt1121_2,
#D/C power control:
drivers=dcdu0,dcdu1,

drivers=adctrack,hwptrack,ktrack,sysMonAOC,observers,purepyindi_example,maggieo_x,dbIngestAOC,labrules,tcsi,instgraph,
drivers=labCool

[remote]
servers=isICC@aoc_icc_indi,
servers=isRTC@aoc_rtc_indi
#servers=isACC000@aoc_acc000_indi
#servers=isTCSI@aoc_icc_istcsi

