[local]
drivers=camwfs,camwfs-dark,camwfs-sw,camwfs-slopes,camwfs-avg,camwfs-fit,camwfs-align,camwfs-refrms,camwfs-refsub-avg,camwfs-photons,fxngensync,fxngenmodwfs,modwfs,
drivers=dmwoofer,dmwoofer-avg,dmwoofer-recon,
drivers=dmtweeter,dmtweeter-avg,dmtweeter-recon,rhtweeter,
drivers=ttmpupil,wooferModes,tweeterModes,t2wOffloader,w2tcsOffloader,sysMonRTC,
drivers=tweeterSpeck,tweeterMod,
drivers=dlReconstructor,hoPredCtrl,tweeterModulator,aol1_modevalWFS-sw,turbsim,zaberLLRTC,stageff,aol1_modevalDM-sw,aol1_modevalWFS_cbuff,aol1_modevalDM_cbuff,wloop,wgainctrl,ttmperi,usbdu0,fwtelsim,
drivers=camtip,camtip-sw,camtip-dark,camtip-avg,
drivers=camacq,camacq-dark,camacq-avg,camacq-sw,camacq-acq,
drivers=flipacq,flipwfsf,fliptip,
drivers=dm00disp-sw,dm00disp01-sw,dm00disp03-sw,
drivers=dm01disp-sw,dm01disp02-sw,dm01disp03-sw,
drivers=holoop,hogainctrl,hopsds,hogopt,hofilt,
drivers=dbIngestRTC,twAlign-camwfs-wfs,twAlign-camwfs-ctrl,sparkleTimer,
drivers=strehl,camtipSR,loPredCtrl,
drivers=acc000-cbuff,acc000-psds,acc000-sw

[remote]
drivers=pdu0@rtc_aoc_indi,pdu1@rtc_aoc_indi,pduhcat@rtc_aoc_indi,dcdu1@rtc_icc_indi,xt1121_2@rtc_icc_indi,pdu2@rtc_aoc_indi,pdu3@rtc_aoc_indi,loloop@rtc_icc_indi,stagecamlensx@rtc_icc_indi,stagecamlensy@rtc_icc_indi,tcsi@rtc_aoc_indi,camsci1@rtc_icc_indi,camsci2@rtc_icc_indi,camflowfs@rtc_icc_indi,stagebs@rtc_icc_indi,acc000@rtc_acc000_indi,observers@rtc_aoc_indi

