[shmimMonitor]
shmimName=aol1_modevalWFS #aoSim_wfs
cpuset=acqu_mvm
threadPrio=50

[framegrabber]
shmimName=aol1_modevalPRC #aoSim_dm
cpuset=acqu_mvm
threadPrio=45

[parameters]
gain = 0.3
copy_gain = 1.0
regularization = 100.0
gamma = 1.00
covariance = 1e-5
history = 15
future = 3
num_modes = 2
fpsSource = camwfs
own_shmim = true
qrd = true