[shmimMonitor]
shmimName=aoSim_wfs
cpuset=acqu_mvm
threadPrio=50

[framegrabber]
shmimName=aoSim_dm
cpuset=acqu_mvm
threadPrio=45


[parameters]
gain = 0.5
regularization = 100.0
gamma = 1.001
covariance = 100000.0
history = 10
future = 3
num_modes = 15
fpsSource = camwfs