[server]
shmimNames=camwfs,camwfs_dark,camwfs_slopes,camwfs_avg,camwfs_thresh,camwfs_edge,camwfs_ref,camwfs_refc,camwfs_refsub_avg,
shmimNames=dm00disp,dm00disp00,dm00disp01,dm00disp02,dm00disp03,dm00disp04,dm00disp05,dm00disp06,dm00disp07,dm00disp08,dm00disp09,dm00disp10,dm00disp11,dm00dispST,dm00dispSP,dm00disp_shape,dm00disp_delta,dmwoofer_avg,
shmimNames=dm01disp,dm01disp00,dm01disp01,dm01disp02,dm01disp03,dm01disp04,dm01disp05,dm01disp06,dm01disp07,dm01disp08,dm01disp09,dm01disp10,dm01disp11,dm01dispST,dm01dispSP,dm01disp_delta,dm01disp_shape,dmtweeter_avg,
shmimNames=dm02disp,dm02disp00,dm02disp01,dm02disp02,dm02disp03,dm02disp04,dm02disp05,dm02disp06,dm02disp07,dm02disp08,dm02disp09,dm02disp10,dm02disp11,dm02dispST,dm02dispSP,dmncpc_avg,
shmimNames=camsci1,camsci1_dark,camsci1_avg,
shmimNames=camsci2,camsci2_dark,camsci2_avg,
shmimNames=camdurham,camdurham_dark,camdurham_avg,
shmimNames=camflowfs,camflowfs_dark,camflowfs_avg,
shmimNames=camllowfs,camllowfs_dark,camllowfs_avg,
shmimNames=camtip,camtip_dark,camtip_avg,
shmimNames=camacq,camacq_dark,camacq_avg,
shmimNames=fdpr_phase,fdpr_amp,
shmimNames=aol1_freq,aol1_clpsds,aol1_olpsds,
shmimNames=twAlign-camwfs-wfs_refIm,twAlign-camwfs-wfs_raw,twAlign-camwfs-wfs_poke,
shmimNames=aol1_mgainfact,aol1_mgainoptimalSI,aol1_mgainoptimalLP,aol1_mmodevar,aol1_clxferSI,aol1_clxferLP,aol1_noisepsds,
shmimNames=acc000_freq,acc000_psds

imagePort=9000
fpsTgt=0.5
usecSleep=10000
compress=true
