[server]
address=localhost
imagePort=9000
shmimNames=aol1_freq,aol1_clpsds,aol1_olpsds,aol1_mmodevar,aol1_noisepsds,aol1_clxferSI,aol1_clxferLP,aol1_clxferCurrent,aol1_mgainfact,aol1_mgainoptimalSI,
shmimNames=acc000_freq,acc000_psds,aol1_imWFS2_cbuff


