[server]
address=rtc
imagePort=5556
shmimNames=camtip,camtip_dark,camtip_avg,
shmimNames=camacq,camacq_dark,camacq_avg,
shmimNames=camwfs_dark,camwfs_ref,camwfs_refc,camwfs_refsub_avg,camwfs_mask,camwfs_slopes,camwfs_avg,camwfs_edge,camwfs_photons,
shmimNames=dm00disp,dm00disp00,dm00disp01,dm00disp02,dm00disp03,dm00disp04,dm00disp05,dm00disp06,dm00disp07,dm00disp08,dm00disp09,dm00disp10,dm00disp11,dm00dispST,dm00dispSP,dm00disp_shape,dm00disp_delta,dmwoofer_avg,
shmimNames=dm01disp,dm01disp00,dm01disp01,dm01disp02,dm01disp03,dm01disp04,dm01disp05,dm01disp06,dm01disp07,dm01disp08,dm01disp09,dm01disp10,dm01disp11,dm01dispST,dm01dispSP,dm01disp_shape,dm01disp_delta,dmtweeter_avg,
shmimNames=fdpr_camsci2_phase,fdpr_camsci2_amp,fdpr2_amp,fdpr2_phase,
shmimNames=aol1_freq,aol1_clpsds,aol1_olpsds,aol1_mmodevar,aol1_noisepsds,aol1_clxferSI,aol1_clxferLP,aol1_clxferCurrent,aol1_mgainfact,aol1_mgainoptimalSI,
shmimNames=acc000_freq,acc000_psds,aol1_imWFS2_cbuff


