[input]
device=ncpcAlign-pupil-wfs
property=measurement
elements=delta_x,delta_y
counterElement=counter
references=-1.91,1.09

[ctrl]
devices=ttmperi,ttmperi
properties=axis1_voltage,axis2_voltage
operatingOK=true

[loop]
intMat00=-19.07
intMat01=-2.56
intMat10=4.35
intMat11=16.21
gain=0.1
gains=1,1



