[stream]
writers=camsci1,camsci2,camtip,camflowfs,camllowfs,camwfs,camacq,dm00disp,dm01disp,dm01disp02,dm01disp03,dm02disp,dm02disp03,aol1_modevalWFS,aol2_modevalWFS,acc000

[jrmales@arizona.edu]
pfoa=Jared
full_name=Jared R. Males
institution=University of Arizona

[lclose@as.arizona.edu]
pfoa=Laird
full_name=Laird M. Close
institution=University of Arizona

[haffert@strw.leidenuniv.nl]
pfoa=Sebastiaan
full_name=Sebastiaan Y. Haffert
institution=Leiden Observatory

[jlong@flatironinstitute.org]
pfoa=Joseph
full_name=Joseph D. Long
institution=Flatiron Institute

[lapearce@umich.edu]
pfoa=Logan
full_name=Logan A. Pearce
institution=University of Arizona

[jeisner@arizona.edu]
pfoa=Josh
full_name=Josh Eisner
institution=University of Arizona

[aweinberger@carnegiescience.edu]
pfoa=Alycia
pronunciation=uhLeesh ah
full_name=Alycia Weinberger
institution=Carnegie Institution for Science

[lperez@uas.uchile.cl]
pfoa=Laura
full_name=Laura Perez
institution=Universidad de Chile

[mrmeyer@umich.edu]
pfoa=Michael
full_name=Michael Meyer
institution=University of Michigan

[vizzy@xwcl.science]
pfoa=Vizzy
full_name=Vizzctor V. Viscacha
institution=Las Campanas Observatory

[warrenbfoster@arizona.edu]
pfoa=Warren
full_name=Warren Foster
institution=The University of Arizona

[edenmcewen@arizona.edu]
pfoa=Eden
full_name=Eden McEwen
institution=The University of Arizona

[jialinli@arizona.edu]
pfoa=Jialin
full_name=Li
institution=The University of Arizona

[gcugno@umich.edu]
pfoa=Gabriele
full_name=Gabriele Cugno
institution=University of Michigan

[jliberman@arizona.edu]
pfoa=Josh
full_name=Josh Liberman
institution=University of Arizona

[jkueny@arizona.edu]
pfoa=Jay
full_name=Jay Kueny
institution=University of Arizona

[jrhom@arizona.edu]
pfoa=Justin
full_name=Justin Hom
institution=University of Arizona

[parkertjohnson1@arizona.edu]
pfoa=Parker
full_name=Parker Johnson
institution=University of Arizona

[twitchell@arizona.edu]
pfoa=Katie
full_name=Katie Twitchell
institution=University of Arizona

[tonucci@strw.leidenuniv.nl]
pfoa=Elena
full_name=Elena Tonucci
institution=Leiden Observatory

[yzhou@virginia.edu]
pfoa=Yifan
pronunciation=yee fahn
full_name=Yifan Zhou
institution=University of Virginia

[mars@strw.leidenuniv.nl]
pfoa=Matthijs
pronunciation=mat tias
full_name=Matthijs Mars
institution=Leiden University

[perezl1@arizona.edu]
pfoa=Lauren
full_name=Lauren Perez
institution=University of Arizona

[tiffanytn@arizona.edu]
pfoa=Tiffany
full_name=Tiffany Nguyen
institution=University of Arizona

[mileslucas@arizona.edu]
pfoa=Miles
full_name=Miles Lucas
institution=University of Arizona

[lalbrow@mit.edu]
pfoa=Leah
full_name=Leah Albrow
institution=Massachusetts Institute of Technology
