[camera]
shmim = "camsci1"
dark_shmim = "camsci1_dark"
stagepos = 54.5

[dm]
shmim = 'dmncpc'
channel = 6

[calibration]
path = '/opt/MagAOX/calib/coron-pupil/'
fwpupil_modes = ['bump-mask',]
fwlyot_modes = ['LyotLg1',]