satLevel=65535

[image]
key=camdurham

[dark]
key=camdurham_dark

[indi]
ipAddress=127.0.0.1
port=7624

[camera]
name=camdurham
filterDevices=fwfpm,stagevp,stageirf

[north]
scale=-1
offset=0

#[rules]
#device=labrules
#cautions=

