targetXc=0.6001
targetYc=0.4668

satLevel=1023

[image]
key=camtip

[dark]
key=camtip_dark

[indi]
ipAddress=127.0.0.1
port=7624

[camera]
name=camtip
filterDevices=stagebs,flipwfsf,fliptip

[north]
enabled=false
