satLevel=65535

[image]
key=camsci1

[dark]
key=camsci1_dark

[indi]
ipAddress=127.0.0.1
port=7624

[camera]
name=camsci1
filterDevices=fwscind,stagescibs,stagesci1,fwsci1

[north]
scale=-1
offset=180

[rules]
device=labrules
cautions=camsci1-on-not-focused,camsci1-on-not-operating,camsci1-sw-not-writing,stagesci1-warn,stagescibs-warn

