satLevel=1023

targetXc=0.502
targetYc=0.6289


[image]
key=camacq_avg

[indi]
ipAddress=127.0.0.1
port=7624

[camera]
name=camacq
filterDevices=flipacq

[north]
enabled=false

[acquisition]
fitter=camacq-acq
camera=camacq
radius=30
