satLevel=16383

[image]
key=camwfs

[dark]
key=camwfs_dark

[indi]
ipAddress=127.0.0.1
port=7624

[camera]
name=camwfs
filterDevices=fwtelsim,stagebs,flipwfsf,fliptip

[pwfsAlignment]
name=camwfs-fit

[north]
enabled=false

[rules]
device=labrules
cautions=cal-src-on-not-labmode,flipwfsf-in-not-labmode,ho-loop-closed-not-synchro,instCool-flow-caution,instCool-temp-caution
warnings=instCool-flow-warning,instCool-temp-warning,camwfs-emprotect-tripped
alerts=instCool-flow-alert,instCool-temp-alert



