satLevel=65535

[image]
key=camsci2

[dark]
key=camsci2_dark

[indi]
ipAddress=127.0.0.1
port=7624

[camera]
name=camsci2
filterDevices=fwscind,stagescibs,stagesci2,fwsci2

[north]
scale=-1
offset=180

[rules]
device=labrules
cautions=camsci2-on-not-operating,camsci2-sw-not-writing,stagesci2-warn,stagescibs-warn

