[stage]
maxCounts=771029
powerOnHome=true
#presets start from 1
homePreset=3

[presets]
names=      min, knifemask-out, knifemask-ri, knifemask-pol, lyotsm-out, lyotsm-ri, lyotsm-pol, lyotlg-out, lyotlg-ri, lyotlg-pol,  test, max
positions=  0,            44.0,         50.5,          53.5,       46.5,      53.0,       56.0,       47.5,      54.0,       57.0, 65.5, 76.5


