[stage]
maxCounts=1526940
powerOnHome=true
#presets start from 1
homePreset=2

[presets]
names=      min,  knifemask-out, knifemask-ri, knifemask-pol, lyotsm-out, lyotsm-ri, lyotsm-pol, lyotlg-out, lyotlg-ri, lyotlg-pol,  max
positions=  0,             44.0,         53.0,         56.0,        46.5,      52.5,       55.5,       47.5,      53.5,       56.5, 151.5


