[stage]
maxCounts=771029
powerOnHome=true
#presets start from 1
homePreset=2

[presets]
names=min,fpm,jtest-telsim,straight-thru,straight-thru-knife,straight-thru-telsim,max
positions=0,47.5,55.2,44.0,41,48.7,76.5

#names=      min, km_out,  km_ri,km_pol,ls_out,ls_ri,ls_pol,ll_out,ll_ri,ll_pol
#positions=  0,   44.0,   


