[stage]
maxCounts=1526940
#1007881
powerOnHome=true
#presets start from 1
homePreset=3

[presets]

#commas after each entry except last one

names=     min,  
positions=   0,  

names=     max, 
positions=   100,          

names=     6535-open-ir, 
positions=   44.0,           

names=     6535-open-pol, 
positions=   51.5,              

names=     6535-open-out, 
positions=   44.0,     #no light     

names=     6535-knife-ir, 
positions=   44.0,           

names=     6535-knife-pol, 
positions=   51.5,              

names=     6535-knife-out, 
positions=   44.0,     #no light     

names=     6535-lytlg-ir, 
positions=   47.0,            

names=     6535-lyotlg-pol, 
positions=   51.5,               

names=     6535-lyotlg-out, 
positions=   47.0,   #no light           

names=     6535-lyotsm-ir, 
positions=   46.5,            

names=     6535-lyotsm-pol, 
positions=   52.0,               

names=     6535-lyotsm-out, 
positions=   46.5, #no light          

names=     hair-open-ha, 
positions=   44.0,          

names=     hair-open-ri, 
positions=   43.0,          

names=     hair-knife-ha, 
positions=   44.0,          

names=     hair-knife-ri, 
positions=   43.0,          

names=     hair-lytlg-ha, 
positions=   47.0,          

names=     hair-lytlg-ir,
positions=   46.5,          

names=     hair-lytsm-ha, 
positions=   46.0,         

names=     hair-lytsm-ir
positions=   45.0

#no comma on last one