[power]
device=pdu1
channel=stagesmc
#channel=stagecamlensy

[usb]
idVendor=0403
idProduct=6001
#serial=A9P665VZ
#serial=A506PIWT
serial=A9OQIKN5

[stage]
powerOnHome=true
homingOffset=-60
opDelta=0.1

[presets]
names=lab
positions=-60
