[stage]
maxCounts=1526940
#1007881
powerOnHome=true
#presets start from 1
homePreset=2

[presets]
names=     min,  max, 6535-knife-ir, 6535-knife-pol, 6535-knife-out, 6535-lytlg-ir, 6535-lyotlg-pol, 6535-lyotlg-out, 6535-lyotsm-ir, 6535-lyotsm-pol, 6535-lyotsm-out, hair-knife-ha, hair-knife-ri, hair-lytlg-ha, hair-lytlg-ir, hair-lytsm-ha, hair-lytsm-ir
positions=   0,  100,          44.0,           51.5,              0,          47.0,            51.5,               0,           46.5,            52.0,               0,          44.0,          43.0,          47.0,          46.5,          46.0,         45.0

