[stage]
maxCounts=771029
powerOnHome=true
#presets start from 1
homePreset=4

[presets]
names=      test, min,  max, 6535-knife-ri, 6535-knife-pol, 6535-knife-out, 6535-lyotlg-ri, 6535-lyotlg-pol, 6535-lyotlg-out, 6535-lyotsm-ri, 6535-lyotsm-pol, 6535-lyotsm-out, hair-knife-ha, hair-knife-ri, hair-lyotlg-ha, hair-lyotlg-ri, hair-lyotsm-ha, hair-lyotsm-ri
positions=  65.5,   0, 76.5,          47.0,           50.0,           41.0,          50.0,            52.0,            43.0,           49.0,            51.0,            43.0,          44.5,          45.5,          49.0,          49.0,          48.0,         47.5

#commas after each entry except last one
names=      test, 
positions=  65.5,   

names= min,  
positions= 0,                                                                                                 

names= max, 
positions= 76.5,

names= 6535-open-ir, 
positions= 47.0, 

names= 6535-open-pol, 
positions= 50.0,

names= 6535-open-out, 
positions= 41.0,

names= 6535-knife-ir, 
positions= 47.0, 

names= 6535-knife-pol, 
positions= 50.0,

names= 6535-knife-out, 
positions= 41.0,

names= 6535-lytlg-ir,
positions= 50.0,

names= 6535-lyotlg-pol, 
positions= 52.0,

names= 6535-lyotlg-out, 
positions= 43.0,

names= 6535-lyotsm-ir, 
positions= 49.0,

names= 6535-lyotsm-pol, 
positions= 51.0,

names= 6535-lyotsm-out, 
positions= 43.0,                                                         

names= hair-open-ha, 
positions=  44.5,

names= hair-open-ri, 
positions= 45.5,

names= hair-knife-ha, 
positions=  44.5,

names= hair-knife-ri, 
positions= 45.5,

names= hair-lytlg-ha, 
positions= 49.0,

names= hair-lytlg-ir, 
positions= 49.0,

names= hair-lytsm-ha, 
positions= 48.0,

names= hair-lytsm-ir
positions= 47.5

#no comma on last one
