#Configuration of Zaber stage low-level controller

[power]
device=pdu2
channel=stagezaber

[usb]
idVendor=0403
idProduct=6001
serial=AH06166Q

[stagesci1]
serial=49822

[stagevp]
serial=141812

[stagesci2]
serial=49820

[stageflowfs]
serial=49821

[stagescibs]
serial=49850

[stagepiaa]
serial=104971

[stagelosel]
serial=49849

[stageipiaa]
serial=104970

[stagebs]
serial=64040


