################################
# Rules for camsci focus checks
###############################


#check fwscind position is not pupil
[fwscind-not-pupil]
ruleType=swVal
property=fwscind.filterName
element=pupil
target=Off

#### camsci1/stagesci1

#check if stagesci1 position does not match coronagraph setup
[stagesci1-focus-mismatch]
ruleType=multiSwitchCombo
numSwitches=3
property1=stagebs.presetName
property2=fwfpm.filterName
property3=stagescibs.presetName
format="{}-{}-{}"
targetProperty=stagesci1.presetName


#check if stagesci1 is not focused and not in pupil mode
[stagesci1-not-focused-not-pupil]
ruleType=ruleComp
rule1=fwscind-not-pupil
rule2=stagesci1-focus-mismatch

#check if camsci1 is operating
[camsci1-operating]
ruleType=txtVal
property=camsci1.fsm
element=state
comp=Eq
target=OPERATING

#check if we're not focused but the camera is operating
[camsci1-on-not-focused]
ruleType=ruleComp
rule1=camsci1-operating
rule2=stagesci1-not-focused-not-pupil
priority=caution
message="camsci1 is not in focus"


#### camsci2/stagesci2

#check if stagesci2 position does not match coronagraph setup
[stagesci2-focus-mismatch]
ruleType=multiSwitchCombo
numSwitches=3
property1=stagebs.presetName
property2=fwfpm.filterName
property3=stagescibs.presetName
format="{}-{}-{}"
targetProperty=stagesci2.presetName

#check if stagesci2 is not focused and not in pupil mode
[stagesci2-not-focused-not-pupil]
ruleType=ruleComp
rule1=fwscind-not-pupil
rule2=stagesci2-focus-mismatch

#check if camsci2 is operating
[camsci2-operating]
ruleType=txtVal
property=camsci2.fsm
element=state
comp=Eq
target=OPERATING

#check if we're not focused but the camera is operating
[camsci2-on-not-focused]
ruleType=ruleComp
rule1=camsci2-operating
rule2=stagesci2-not-focused-not-pupil
priority=caution
message="camsci2 is not in focus"




