##################################
# environment rules

#These rules monitor tweeter humidity
[rhtweeter-caution]
ruleType=numVal
priority=caution
comp=GtEq
property=rhtweeter.humidity
element=current
target=12

[rhtweeter-warning]
ruleType=numVal
priority=warning
comp=GtEq
property=rhtweeter.humidity
element=current
target=15

[rhtweeter-alert]
ruleType=numVal
priority=alert
comp=GtEq
property=rhtweeter.humidity
element=current
target=18

#These rules monitor ncpc humidity
[rhncpc-caution]
ruleType=numVal
priority=caution
comp=GtEq
property=rhhcpc.humidity
element=current
target=12

[rhncpc-warning]
ruleType=numVal
priority=warning
comp=GtEq
property=rhtweeter.humidity
element=current
target=15

[rhncpc-alert]
ruleType=numVal
priority=alert
comp=GtEq
property=ncpc.humidity
element=current
target=18

#Monitor instCool
[instCool-flow-caution]
ruleType=numVal
priority=caution
comp=LtEq
property=instCool.status
element=flow_rate
target=2.0

[instCool-flow-warning]
ruleType=numVal
priority=warning
comp=LtEq
property=instCool.status
element=flow_rate
target=1.8

[instCool-flow-alert]
ruleType=numVal
priority=alert
comp=LtEq
property=instCool.status
element=flow_rate
target=1.5

[instCool-temp-caution]
ruleType=numVal
priority=caution
comp=GtEq
property=instCool.status
element=liquid_temp
target=28

[instCool-temp-warning]
ruleType=numVal
priority=warning
comp=GtEq
property=instCool.status
element=liquid_temp
target=30

[instCool-temp-alert]
ruleType=numVal
priority=alert
comp=GtEq
property=instCool.status
element=liquid_temp
target=32

#monitor temp rack
[temprack-upper-caution]
ruleType=numVal
priority=caution
comp=GtEq
property=temprack.temperature
element=upper
target=30

[temprack-upper-warning]
ruleType=numVal
priority=warning
comp=GtEq
property=temprack.temperature
element=upper
target=32

[temprack-upper-alert]
ruleType=numVal
priority=alert
comp=GtEq
property=temprack.temperature
element=upper
target=35

[temprack-lower-caution]
ruleType=numVal
priority=caution
comp=GtEq
property=temprack.temperature
element=lower
target=28

[temprack-lower-warning]
ruleType=numVal
priority=warning
comp=GtEq
property=temprack.temperature
element=lower
target=30

[temprack-lower-alert]
ruleType=numVal
priority=alert
comp=GtEq
property=temprack.temperature
element=lower
target=32
