#######################################
# 

[ho-loop-closed]
ruleType=swVal
property=holoop.loop_state
element=toggle
target=On

[camwfs-not-synchro]
ruleType=swVal
property=camwfs.synchro
element=toggle
comp=Neq
target=On

[ho-loop-closed-not-synchro]
ruleType=ruleComp
rule1=ho-loop-closed
rule2=camwfs-not-synchro
comp=And
priority=caution
message="Loop is closed without camwfs synchro."

[camwfs-emprotect-tripped]
ruleType=txtVal
property=camwfs.emProtection
element=status
target=TRIPPED
priority=warning
message="camwfs EM gain protection is tripped"

[camwfs-emprotect-unkown]
ruleType=txtVal
property=camwfs.emProtection
element=status
target=UNKNOWN
priority=info
message="camwfs EM gain protection is unknown"

[camwfs-fps-above-2kHz]
ruleType=numVal
property=camwfs.fps
element=current
target=2000
comp=Gt

[camwfs-fps-below-1kHz]
ruleType=numVal
property=camwfs.fps
element=current
target=1000
comp=Lt


[loop-closed-above-2kHz]
ruleType=ruleComp
rule1=ho-loop-closed
rule2=camwfs-fps-above-2kHz
comp=And
priority=info
message="The loop is closed above 2kHz"

[loop-closed-below-1kHz]
ruleType=ruleComp
rule1=ho-loop-closed
rule2=camwfs-fps-below-1kHz
comp=And
priority=info
message="The loop is closed below 1kHz"


