#######################################
# 

[ho-loop-closed]
ruleType=swVal
property=holoop.loop_state
element=toggle
target=On

[camwfs-not-synchro]
ruleType=swVal
property=camwfs.synchro
element=toggle
comp=Neq
target=On

[ho-loop-closed-not-synchro]
ruleType=ruleComp
rule1=ho-loop-closed
rule2=camwfs-not-synchro
comp=And
priority=caution
message="Loop is closed without camwfs synchro."

