#test if stagezaber power is on
[stagezaber-pwr-on]
ruleType=txtVal
property=pdu2.stagezaber
element=state
target=On

#test if stagezaber state is 10 min old 
[stagezaber-state-10min]
ruleType=timeDiff
property=pdu2.stateTimes
element=stagezaber
target=600
comp=Gt

#test if stagezaber power has been on for more than 10 min
#[stagezaber-pwr-on-10min]
#ruleType=ruleComp
#rule1=stagezaber-pwr-on
#rule2=stagezaber-state-10min
#comp=And
#priority=caution
#message="stagezaber power has been on for more than 10 minutes"


