#This rule tests if stagebs has a warning
[stagebs-warn]
ruleType=swVal
priority=caution
property=zaberLowLevel.warning
element=stagebs
target=On

#This rule tests if stageflowfs has a warning
[stageflowfs-warn]
ruleType=swVal
priority=caution
property=zaberLowLevel.warning
element=stageflowfs
target=On

#This rule tests if stageipiaa has a warning
[stageipiaa-warn]
ruleType=swVal
priority=caution
property=zaberLowLevel.warning
element=stageipiaa
target=On

#This rule tests if stagelosel has a warning
[stagelosel-warn]
ruleType=swVal
priority=caution
property=zaberLowLevel.warning
element=stagelosel
target=On

#This rule tests if stagepiaa has a warning
[stagepiaa-warn]
ruleType=swVal
priority=caution
property=zaberLowLevel.warning
element=stagepiaa
target=On

#This rule tests if stagesci1 has a warning
[stagesci1-warn]
ruleType=swVal
priority=caution
property=zaberLowLevel.warning
element=stagesci1
target=On

#This rule tests if stagesci2 has a warning
[stagesci2-warn]
ruleType=swVal
priority=caution
property=zaberLowLevel.warning
element=stagesci2
target=On

#This rule tests if stagescibs has a warning
[stagescibs-warn]
ruleType=swVal
priority=caution
property=zaberLowLevel.warning
element=stagescibs
target=On




