#test if stagebs hasn't been homed in 22 hrs
[stagebs-home-22hrs]
ruleType=timeDiff
priority=caution
message=stagebs needs to be homed
property=stagebs.last_homed
element=time_sec
target=79200
comp=Gt

#test if stagebs hasn't been homed in 46 hrs
[stagebs-home-46hrs]
ruleType=timeDiff
priority=warning
message=stagebs really needs to be homed
property=stagebs.last_homed
element=time_sec
target=165600
comp=Gt

#test if stagepiaa hasn't been homed in 22 hrs
[stagepiaa-home-22hrs]
ruleType=timeDiff
priority=caution
message=stagepiaa needs to be homed
property=stagepiaa.last_homed
element=time_sec
target=79200
comp=Gt

#test if stagepiaa hasn't been homed in 46 hrs
[stagepiaa-home-46hrs]
ruleType=timeDiff
priority=warning
message=stagepiaa really needs to be homed
property=stagepiaa.last_homed
element=time_sec
target=165600
comp=Gt

#test if stageflowfs hasn't been homed in 22 hrs
[stageflowfs-home-22hrs]
ruleType=timeDiff
priority=caution
message=stageflowfs needs to be homed
property=stageflowfs.last_homed
element=time_sec
target=79200
comp=Gt

#test if stageflowfs hasn't been homed in 46 hrs
[stageflowfs-home-46hrs]
ruleType=timeDiff
priority=warning
message=stageflowfs really needs to be homed
property=stageflowfs.last_homed
element=time_sec
target=165600
comp=Gt

#test if stagelosel hasn't been homed in 22 hrs
[stagelosel-home-22hrs]
ruleType=timeDiff
priority=caution
message=stagelosel needs to be homed
property=stagelosel.last_homed
element=time_sec
target=79200
comp=Gt

#test if stageflowfs hasn't been homed in 46 hrs
[stagelosel-home-46hrs]
ruleType=timeDiff
priority=warning
message=stagelosel really needs to be homed
property=stagelosel.last_homed
element=time_sec
target=165600
comp=Gt

#test if stageipiaa hasn't been homed in 22 hrs
[stageipiaa-home-22hrs]
ruleType=timeDiff
priority=caution
message=stageipiaa needs to be homed
property=stageipiaa.last_homed
element=time_sec
target=79200
comp=Gt

#test if stageipiaa hasn't been homed in 46 hrs
[stageipiaa-home-46hrs]
ruleType=timeDiff
priority=warning
message=stageipiaa really needs to be homed
property=stageipiaa.last_homed
element=time_sec
target=165600
comp=Gt

#test if stagevp hasn't been homed in 22 hrs
[stagevp-home-22hrs]
ruleType=timeDiff
priority=caution
message=stagevp needs to be homed
property=stagevp.last_homed
element=time_sec
target=79200
comp=Gt

#test if stagevp hasn't been homed in 46 hrs
[stagevp-home-46hrs]
ruleType=timeDiff
priority=warning
message=stagevp really needs to be homed
property=stagevp.last_homed
element=time_sec
target=165600
comp=Gt

#test if stagescibs hasn't been homed in 22 hrs
[stagescibs-home-22hrs]
ruleType=timeDiff
priority=caution
message=stagescibs needs to be homed
property=stagescibs.last_homed
element=time_sec
target=79200
comp=Gt

#test if stagescibs hasn't been homed in 46 hrs
[stagescibs-home-46hrs]
ruleType=timeDiff
priority=warning
message=stagescibs really needs to be homed
property=stagescibs.last_homed
element=time_sec
target=165600
comp=Gt

#test if stagesci1 hasn't been homed in 22 hrs
[stagesci1-home-22hrs]
ruleType=timeDiff
priority=caution
message=stagesci1 needs to be homed
property=stagesci1.last_homed
element=time_sec
target=79200
comp=Gt

#test if stagesci1 hasn't been homed in 46 hrs
[stagesci1-home-46hrs]
ruleType=timeDiff
priority=warning
message=stagesci1 really needs to be homed
property=stagesci1.last_homed
element=time_sec
target=165600
comp=Gt

#test if stagesci2 hasn't been homed in 22 hrs
[stagesci2-home-22hrs]
ruleType=timeDiff
priority=caution
message=stagesci2 needs to be homed
property=stagesci2.last_homed
element=time_sec
target=79200
comp=Gt

#test if stagesci2 hasn't been homed in 46 hrs
[stagesci2-home-46hrs]
ruleType=timeDiff
priority=warning
message=stagesci2 really needs to be homed
property=stagesci2.last_homed
element=time_sec
target=165600
comp=Gt