#test if stagebs hasn't been homed in 26 hrs
[stagebs-home-26hrs]
ruleType=timeDiff
priority=caution
message=stagebs needs to be homed
property=stagebs.last_homed
element=time_sec
target=93600
comp=Gt

#test if stagepiaa hasn't been homed in 26 hrs
[stagepiaa-home-26hrs]
ruleType=timeDiff
priority=caution
message=stagepiaa needs to be homed
property=stagepiaa.last_homed
element=time_sec
target=93600
comp=Gt

#test if stageflowfs hasn't been homed in 26 hrs
[stageflowfs-home-26hrs]
ruleType=timeDiff
priority=caution
message=stageflowfs needs to be homed
property=stageflowfs.last_homed
element=time_sec
target=93600
comp=Gt

#test if stagelosel hasn't been homed in 26 hrs
[stagelosel-home-26hrs]
ruleType=timeDiff
priority=caution
message=stagelosel needs to be homed
property=stagelosel.last_homed
element=time_sec
target=93600
comp=Gt

#test if stageipiaa hasn't been homed in 26 hrs
[stageipiaa-home-26hrs]
ruleType=timeDiff
priority=caution
message=stageipiaa needs to be homed
property=stageipiaa.last_homed
element=time_sec
target=93600
comp=Gt

#test if stagevp hasn't been homed in 26 hrs
[stagevp-home-26hrs]
ruleType=timeDiff
priority=caution
message=stagevp needs to be homed
property=stagevp.last_homed
element=time_sec
target=93600
comp=Gt

#test if stagescibs hasn't been homed in 26 hrs
[stagescibs-home-26hrs]
ruleType=timeDiff
priority=caution
message=stagescibs needs to be homed
property=stagescibs.last_homed
element=time_sec
target=93600
comp=Gt

#test if stagesci1 hasn't been homed in 26 hrs
[stagesci1-home-26hrs]
ruleType=timeDiff
priority=caution
message=stagesci1 needs to be homed
property=stagesci1.last_homed
element=time_sec
target=93600
comp=Gt

#test if stagesci2 hasn't been homed in 26 hrs
[stagesci2-home-26hrs]
ruleType=timeDiff
priority=caution
message=stagesci2 needs to be homed
property=stagesci2.last_homed
element=time_sec
target=93600
comp=Gt

#test if stagepollin hasn't been homed in 26 hrs
[stagepollin-home-26hrs]
ruleType=timeDiff
priority=caution
message=stagepollin needs to be homed
property=stagepollin.last_homed
element=time_sec
target=93600
comp=Gt

#test if stageqwplin hasn't been homed in 26 hrs
[stageqwplin-home-26hrs]
ruleType=timeDiff
priority=caution
message=stageqwplin needs to be homed
property=stageqwplin.last_homed
element=time_sec
target=93600
comp=Gt

#test if stageirf hasn't been homed in 26 hrs
[stageirf-home-26hrs]
ruleType=timeDiff
priority=caution
message=stageirf needs to be homed
property=stageirf.last_homed
element=time_sec
target=93600
comp=Gt





